cabal-version: 3.14
name: cahier-content
version: 0.6.0
license: BSD-3-Clause
license-file: LICENSE
author: Brian J. Gamble
maintainer: brianjgamble@users.noreply.github.com
category: Text
build-type: Simple
extra-doc-files: CHANGELOG.md

common warnings
  ghc-options: -Wall

library cahier-content-internal
  import: warnings
  hs-source-dirs: src-internal
  exposed-modules:
    Cahier.Content.Cache
    Cahier.Content.Files
    Cahier.Content.Parse
    Cahier.Content.Types
    Cahier.Content.Util

  build-depends:
    aeson >=2.2.3 && <2.3,
    base >=4.21 && <5,
    commonmark >=0.2.6 && <0.3,
    commonmark-extensions >=0.2.6 && <0.3,
    containers >=0.7 && <0.8,
    directory >=1.3.9 && <1.4,
    filepath >=1.5.4 && <1.6,
    text >=2.1.2 && <2.2,
    time >=1.14 && <1.15,
    yaml >=0.11.11 && <0.12,

  default-extensions:
    DeriveGeneric
    DuplicateRecordFields
    OverloadedStrings
    StrictData

  default-language: GHC2024

library
  import: warnings
  hs-source-dirs: src
  exposed-modules:
    Cahier.Content

  build-depends:
    aeson >=2.2.3 && <2.3,
    base >=4.21 && <5,
    cahier-content:cahier-content-internal,
    commonmark >=0.2.6 && <0.3,
    commonmark-extensions >=0.2.6 && <0.3,
    containers >=0.7 && <0.8,
    directory >=1.3.9 && <1.4,
    filepath >=1.5.4 && <1.6,
    text >=2.1.2 && <2.2,
    time >=1.14 && <1.15,
    yaml >=0.11.11 && <0.12,

  default-extensions:
    DeriveGeneric
    DuplicateRecordFields
    OverloadedStrings
    StrictData

  default-language: GHC2024

test-suite cahier-content-test
  -- Import common warning flags.
  import: warnings
  -- Base language which the package is written in.
  default-language: GHC2024
  -- Modules included in this executable, other than Main.
  -- other-modules:
  -- LANGUAGE extensions used by modules in this package.
  -- other-extensions:
  -- The interface type and version of the test suite.
  type: exitcode-stdio-1.0
  -- Directories containing source files.
  hs-source-dirs: test
  -- The entrypoint to the test suite.
  main-is: Spec.hs
  other-modules:
    Cahier.Content.TypesSpec
    Cahier.Content.UtilSpec

  default-extensions:
    BlockArguments
    DuplicateRecordFields
    OverloadedStrings

  build-depends:
    aeson >=2.2.3 && <2.3,
    base ^>=4.21.0.0,
    cahier-content:cahier-content-internal,
    hspec >=2.11.14 && <2.12,
    hspec-discover >=2.11.14 && <2.12,
    text >=2.1.2 && <2.2,
    time >=1.14 && <1.15,

  build-tool-depends:
    hspec-discover:hspec-discover

test-suite core-doctest
  type: exitcode-stdio-1.0
  hs-source-dirs: test
  main-is: Doctest.hs
  default-extensions: OverloadedStrings
  build-depends:
    base >=4.14 && <5,
    doctest >=0.22,

  default-language: GHC2024
